calcul_mfcc:
  letters:
  - a
  - i
  file_path_ta: /Users/noemiekt/Documents/MetaMicro/scripts/ici/ta_ti_i.wav
  file_path_ta_text: /Users/noemiekt/Documents/MetaMicro/scripts/ici/ta_ti_i.txt
  file_path_txt_non_concat: /Users/noemiekt/Documents/MetaMicro/scripts/ici/test.txt
  file_path_txt: /Users/noemiekt/Documents/MetaMicro/scripts/ici/text.txt
  file_path_audio_non_concat: /Users/noemiekt/Documents/MetaMicro/scripts/ici/test.wav
  file_path_audio: /Users/noemiekt/Documents/MetaMicro/scripts/ici/audio.wav
  time_of_block: 0.005
  recouvrement_block: 0.5
  pamatres_mfcc:
    n_mfcc: 13
    n_fft: 512
    n_mels: 40
  other_params:
    delta_mfcc: false
    zero_crossing: true
    centroid: false
    slope: true
  output_path: /Users/noemiekt/Documents/MetaMicro/scripts/ici/mfcc_features_marqueurs.csv
correction_avant_classification:
  seuil_de_correction: 0.7
  output_path: /Users/noemiekt/Documents/MetaMicro/scripts/ici/mfcc_features_marqueurs_corrigez.csv
classification:
  if_suppression_mfcc:
    suppression_mfcc: false
    seuil_pour_mfcc_max: 0.45
    eigenvectors_output: null
    eigenvectors_output_tronque: /Users/noemiekt/Documents/MetaMicro/scripts/ici/eigenvectors_tronquemarqueurs.pkl
  dimension_affichage:
  - 0
  - 1
  - 2
  parametres_knn:
    test_size: 0.4
    random_state: 42
    n_neighbors_max: 50
  outputs:
    mean_X_output: /Users/noemiekt/Documents/MetaMicro/scripts/ici/mfcc_mean_test.pkl
    std_X_output: /Users/noemiekt/Documents/MetaMicro/scripts/ici/mfcc_std_test.pkl
    proj_pca_output: /Users/noemiekt/Documents/MetaMicro/scripts/ici/X_proj_scaled_test.csv
    eigenvectors_output: /Users/noemiekt/Documents/MetaMicro/scripts/ici/eigenvectors_test.pkl
    knn_model_output: /Users/noemiekt/Documents/MetaMicro/scripts/ici/knn_model_test.pkl
main_respiro:
  port_name_respiro: IAC Driver Bus 1 Bus 1
  port_name_midifile: IAC Driver Bus 1 Bus 2
  rms_max: 447.1725617700621
  CHANNEL_RESPIRO: 0
  CC_rms: 2
  CC_i: 9
  CC_u: 14
  CC_a: 15
  midi_file: midi/Etude 1.mid
  enregistrement_audio: audio/recorded.wav
  CHANNELS: 1
  RATE: 44100
  batch_size: 6
  recouvrement: 3
  radius: 10
  k: 3
  other_params:
    vide_if_n_label: 
      value: true
      n: 2
    remplacer_t_par_i: 
      value: true 
      n: 5
    

