calcul_mfcc:
  letters:
  - a
  file_path_ta: mac/entrainement_et_meta_micro/ta_ti_i.wav
  file_path_ta_text: mac/entrainement_et_meta_micro/ta_ti_i.txt
  file_path_txt_non_concat: dossier_entrainement/mon_fichier.txt
  file_path_txt: mac/entrainement_et_meta_micro/text.txt
  file_path_audio_non_concat: dossier_entrainement/mon_fichier.wav
  file_path_audio: mac/entrainement_et_meta_micro/audio.wav
  time_of_block: 0.005
  recouvrement_block: 0.5
  pamatres_mfcc:
    n_mfcc: 13
    n_fft: 512
    n_mels: 40
  other_params:
    delta_mfcc: false
    zero_crossing: true
    centroid: false
    slope: true
  output_path: dossier_entrainement/mfcc_features.csv
correction_avant_classification:
  seuil_de_correction: 0.7
  output_path: dossier_entrainement/mfcc_features_marqueurs_corrige.csv
classification:
  if_suppression_mfcc:
    suppression_mfcc: false
    seuil_pour_mfcc_max: 0.45
    eigenvectors_output: null
    eigenvectors_output_tronque: null
  dimension_affichage:
  - 0
  - 1
  - 2
  parametres_knn:
    test_size: 0.4
    random_state: 42
    n_neighbors_max: 50
  outputs:
    mean_X_output: dossier_entrainement/mean_X.csv
    std_X_output: dossier_entrainement/std_X.csv
    proj_pca_output: dossier_entrainement/X_proj_scaled_marqueurs.csv
    eigenvectors_output: dossier_entrainement/eigenvectors_marqueurs.csv
    knn_model_output: dossier_entrainement/knn_model.csv
main_respiro:
  fluidsynth: true
  input_device_index: null
  output_device_index: 4
  canal_midi_sans_respiro: 0
  instrument_sans_respiro: 73
  port_name_respiro: IAC Driver Bus 1 Bus 1
  port_name_midifile: IAC Driver Bus 1 Bus 2
  rms_max: 374.1106605853893
  CHANNEL_RESPIRO: 0
  CC_rms: 2
  CC_i: 9
  CC_u: 14
  CC_a: 15
  midi_file: mac/entrainement_et_meta_micro/midi/Etude 1.mid
  enregistrement_audio: mac/entrainement_et_meta_micro/audio/recorded.wav
  CHANNELS: 1
  RATE: 44100
  batch_size: 6
  recouvrement: 3
  radius: 10
  k: 3
  other_params:
    vide_if_n_label:
      value: true
      n: 2
    remplacer_t_par_i:
      value: false
      n: 5
